version: '3'

services:
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./data-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root